name: kostiantyn_karachentsev_kiyki_21_8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0  
  flutter_riverpod: ^2.0.0
  riverpod: ^2.0.0
  http: ^1.2.2
  firebase_core: ^2.7.0
  firebase_database: ^10.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  

